import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { resourceSchemaOverrides } from "../resource-schemas.ts";
import type {
	GodotClassPropsMetadata,
	GodotEnumMetadata,
	GodotPropsMetadataFile,
} from "./manifest/types.ts";

const metadataPath = resolve(
	process.argv[2] ?? "generated/manifest/godot-4.6-props.json",
);
const outputDir = resolve(process.argv[3] ?? "src/generated");

const builtinRawTypes = new Set([
	"AABB",
	"Basis",
	"Color",
	"Plane",
	"Projection",
	"Quaternion",
	"Rect2",
	"Rect2i",
	"Transform2D",
	"Transform3D",
	"Vector2",
	"Vector2i",
	"Vector3",
	"Vector3i",
	"Vector4",
	"Vector4i",
]);

const packedRawTypes = new Set([
	"PackedByteArray",
	"PackedColorArray",
	"PackedFloat32Array",
	"PackedFloat64Array",
	"PackedInt32Array",
	"PackedInt64Array",
	"PackedStringArray",
	"PackedVector2Array",
	"PackedVector3Array",
	"PackedVector4Array",
]);

function toEnumTypeName(qualifiedName: string) {
	return qualifiedName.replaceAll(".", "_");
}

function toClassPropsName(name: string) {
	return `${name}Props`;
}

function mapType(
	type: string,
	enumRef: string | null,
	isBitfield: boolean,
	resourceClassNames: Set<string>,
	enumNames: Set<string>,
): string {
	if (isBitfield) {
		return "number";
	}

	if (enumRef && enumNames.has(enumRef)) {
		return toEnumTypeName(enumRef);
	}

	if (type.endsWith("[]")) {
		return `${mapType(type.slice(0, -2), null, false, resourceClassNames, enumNames)}[]`;
	}

	if (resourceClassNames.has(type)) {
		return "GodotResourceInput";
	}

	if (builtinRawTypes.has(type)) {
		return "RawValue";
	}

	if (packedRawTypes.has(type)) {
		if (type === "PackedStringArray") {
			return "RawValue | string[]";
		}

		return "RawValue";
	}

	switch (type) {
		case "Array":
			return "SceneValue[]";
		case "bool":
			return "boolean";
		case "Callable":
		case "Dictionary":
		case "Object":
		case "RID":
		case "Signal":
		case "Variant":
			return "SceneValue";
		case "float":
		case "int":
			return "number";
		case "NodePath":
			return "RawValue | string";
		case "String":
		case "StringName":
			return "string";
		default:
			return "SceneValue";
	}
}

function renderEnums(enums: GodotEnumMetadata[]) {
	return enums
		.map((entry) => {
			if (entry.isBitfield) {
				return [
					`export const ${toEnumTypeName(entry.qualifiedName)} = ${JSON.stringify(Object.fromEntries(entry.values.map((value) => [value.name, value.value])), null, 2)} as const;`,
					`export type ${toEnumTypeName(entry.qualifiedName)} = number;`,
				].join("\n");
			}

			return [
				`export const ${toEnumTypeName(entry.qualifiedName)} = ${JSON.stringify(Object.fromEntries(entry.values.map((value) => [value.name, value.value])), null, 2)} as const;`,
				`export type ${toEnumTypeName(entry.qualifiedName)} = (typeof ${toEnumTypeName(entry.qualifiedName)})[keyof typeof ${toEnumTypeName(entry.qualifiedName)}];`,
			].join("\n");
		})
		.join("\n\n");
}

function renderPropsFile(
	classes: GodotClassPropsMetadata[],
	enums: GodotEnumMetadata[],
) {
	const resourceClassNames = classes
		.filter((entry) => entry.kind === "resource")
		.map((entry) => entry.name);
	const instantiableResourceClassNames = classes
		.filter((entry) => entry.kind === "resource" && entry.isInstantiable)
		.map((entry) => entry.name);
	const resourceClassNameSet = new Set(resourceClassNames);
	const enumNames = new Set(enums.map((entry) => entry.qualifiedName));
	const schemaDeclarations = Object.values(resourceSchemaOverrides)
		.flatMap((override) => override.declarations)
		.join("\n");
	const interfaces = classes
		.map((entry) => {
			const heritage = entry.kind === "node" ? " extends SceneNodeProps" : "";
			const schemaProps = resourceSchemaOverrides[entry.name]?.propLines ?? [];
			const members = [
				...entry.allMembers.map(
					(member) =>
						`  ${JSON.stringify(member.name)}?: ${mapType(member.type, member.enumRef, member.isBitfield, resourceClassNameSet, enumNames)};`,
				),
				...schemaProps,
			].join("\n");
			return `export interface ${toClassPropsName(entry.name)}${heritage} {\n${members}${members ? "\n" : ""}}`;
		})
		.join("\n\n");

	return [
		"// Generated by src/codegen/generate-wrappers.ts.",
		'import type { AcutisElement, ExtResourceValue, RawValue, SceneNodeProps, SceneValue, SubResourceValue } from "../core/types.ts";',
		"",
		`export type GodotResourceClassName = ${resourceClassNames.map((name) => JSON.stringify(name)).join(" | ")};`,
		`export type InstantiableGodotResourceClassName = ${instantiableResourceClassNames.map((name) => JSON.stringify(name)).join(" | ")};`,
		"",
		"export type GodotResourceInput = AcutisElement | ExtResourceValue | SubResourceValue | null;",
		"",
		schemaDeclarations || undefined,
		schemaDeclarations ? "" : undefined,
		renderEnums(enums),
		enums.length ? "" : undefined,
		interfaces,
		"",
	]
		.filter((line): line is string => typeof line === "string")
		.join("\n");
}

function renderNodeFile(classes: GodotClassPropsMetadata[]) {
	const lines = [
		"// Generated by src/codegen/generate-wrappers.ts.",
		'import { createNodeType } from "../core/runtime.ts";',
		'import type * as Props from "./props.ts";',
		"",
		...classes.map(
			(entry) =>
				`export const ${entry.name} = createNodeType<Props.${toClassPropsName(entry.name)}>(${JSON.stringify(entry.name)});`,
		),
		"",
	];

	return lines.join("\n");
}

function renderResourceFile(classes: GodotClassPropsMetadata[]) {
	const lines = [
		"// Generated by src/codegen/generate-wrappers.ts.",
		'import { createResourceType } from "../core/runtime.ts";',
		'import type * as Props from "./props.ts";',
		"",
		...classes.map(
			(entry) =>
				`export const ${entry.name} = createResourceType<Props.${toClassPropsName(entry.name)}>(${JSON.stringify(entry.name)});`,
		),
		"",
	];

	return lines.join("\n");
}

function renderIndexFile() {
	return [
		"// Generated by src/codegen/generate-wrappers.ts.",
		'export * from "./props.ts";',
		'export * from "./nodes.ts";',
		'export * from "./resources.ts";',
		"",
	].join("\n");
}

function renderValidationFile(classes: GodotClassPropsMetadata[]) {
	return [
		"// Generated by src/codegen/generate-wrappers.ts.",
		"export const godotAllowedPropNamesByClass = new Map<string, readonly string[]>([",
		...classes.map((entry) => {
			const members = JSON.stringify(
				entry.allMembers
					.map((member) => member.name)
					.sort((a, b) => a.localeCompare(b)),
			);
			return `  [${JSON.stringify(entry.name)}, ${members}],`;
		}),
		"]);",
		"",
	].join("\n");
}

async function main() {
	const metadata = JSON.parse(
		await readFile(metadataPath, "utf8"),
	) as GodotPropsMetadataFile;
	const nodeClasses = metadata.classes.filter(
		(entry) => entry.kind === "node" && entry.isInstantiable,
	);
	const resourceClasses = metadata.classes.filter(
		(entry) => entry.kind === "resource" && entry.isInstantiable,
	);

	await mkdir(outputDir, { recursive: true });

	const propsFile = resolve(outputDir, "props.ts");
	const nodesFile = resolve(outputDir, "nodes.ts");
	const resourcesFile = resolve(outputDir, "resources.ts");
	const indexFile = resolve(outputDir, "index.ts");
	const validationFile = resolve(outputDir, "validate.ts");

	await mkdir(dirname(nodesFile), { recursive: true });
	await writeFile(
		propsFile,
		renderPropsFile(metadata.classes, metadata.enums),
		"utf8",
	);
	await writeFile(nodesFile, renderNodeFile(nodeClasses), "utf8");
	await writeFile(resourcesFile, renderResourceFile(resourceClasses), "utf8");
	await writeFile(indexFile, renderIndexFile(), "utf8");
	await writeFile(
		validationFile,
		renderValidationFile(metadata.classes),
		"utf8",
	);
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
